language: ruby
rvm:
- 2.4
before_install:
- export | grep SAUCE_
env:
  global:
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: VgthGcAE7KLPVeC9WHoRbRUdJc3nFYrA8ugjF5DFU4R1lpKB44V5Yt8V+rKaGFaiVUclH9O9BWkw8K8WlmOlBpPI+1wGZpXrMHRUJxl+KpJQXFrcCOas7dNvJNc89OHlo+2XkAEVQPQLx7nfuh9bbW6u1tb/VDR2V7ThnjVWlIWWA9T65XF7M32hcDgytUYHQZVKeSWpebnERgoTAj5aO8oK3DVCHlq4Q6kxozd9yFp1JrEQZustKJ8bPdOJaSpdZjjCmbrutpTbRl9jB85k/WqvqrWdPEEprarY+si1YaZ00zViNU7womofmzx8JZaWaSoIAPbzjK6fn2tEflau+jorf0wdqbU3Bkfp7AF72m7aDUgSFKXQJgkAgVZUgDLZEyGuowPqa0e2Elt1QAB/BvMc70XanNqu7wpGmPftgHWbD8q5R3lVt/ojxl2yNv3xrAsN0SJ4MzMy15R3l3jx0/78cD2Lb7UEjgQXE27yDbGEqFiBK0pB2j8GcRhNK9dec8PNwQtFWgqc6eDLwmat/8ZbUKAzFDL10rmrX80ZgsZMPDU9eE88lxGjpeQbZe7FKM7qXrBxsKi+veogHB8hB8sJaqbt6Ll/fbaCMLSxQF82Vj1/4q2HN84SBBgt8Mng6tqk76lzyXC5N3YAcdokj2MDfnDkVu5Fnt0lSksWS8o=
